### PR TITLE
Update Footer.tsx to add Joe Banks

### PR DESCRIPTION
**Pull request by john-montgomery2003**
No comment needed. We must, we __must__ have Joe Banks on the thanks list.

Team, thanks.

### CODE REVIEW

**Review by NicholasG04 — CHANGES_REQUESTED** [review]
no

**Comment by john-montgomery2003** [comment]
please

**Comment by Modlizard** [comment]
This space is occupied by the axolotl which is a protected entity, please migrate to a different area.

**Comment by john-montgomery2003** [comment]
> This space is occupied by the axolotl which is a protected entity, please migrate to a different area.

Joe banks

**Pull request closed without merging**
