### PR TITLE
Stripe Online Payments Functionality (#7)

### LINKED ISSUE #7: Stripe Online Payments Support
- [ ] Add Stripe Payment Element
- [ ] Associated API Routes

### PR DESCRIPTION
**Pull request by NicholasG04**
Closes #7

### CODE REVIEW

**Comment by NicholasG04** [comment]
No need to use axios, we can just use fetch instead which is built into Next.js and polyfilled on server. Not sure what this stuff is about getting the secret from a server? We just want to use the Stripe secret in our API routes. Also, need to move loading Stripe into a util file for loading it on multiple pages - we only want to spawn one copy of the stripe promise. Will deal with these now. Thanks Dalu

**Comment by NicholasG04** [comment]
With regards to the checkout form specifically, we don't need to collect all this data here. We have the user's full name from Azure, and I don't think we need anything else that the Payment Element itself won't collect for us. When making the payment, we're going to assume that they don't already have a customer ID (they won't do, they can only ever buy something once) and then just pass in the full name from the Supabase user metadata. Great effort here, but I think we need to start again with quite a bit of this using the Payment Element docs specifically.

Also, we can just use Chakra UI for any other form elements we need - no custom CSS required

**Comment by NicholasG04** [comment]
after buying ticket, should redirect to the user panel which then shows ticket: loading... until it gets a ping from the supabase storage db saying there's an update to their row

**Review by JacquesRW — APPROVED** [review]
take my money

**Pull request merged**
