### PR TITLE
feat: ability to disable purchases

### PR DESCRIPTION
**Pull request by NicholasG04**

### CODE REVIEW

**Comment by Modlizard** [comment]
Very securely done with absolutely no workarounds very good very nice.

**Review by Modlizard — APPROVED** [review]

**Comment by Modlizard** [comment]
Apart from the fact it doesn't work and failed all of the checks.

**Comment by john-montgomery2003** [comment]
> Apart from the fact it doesn't work and failed all of the checks.

smh did you not test fully before approving the changes?

**Comment by Modlizard** [comment]
> > Apart from the fact it doesn't work and failed all of the checks.
> 
> smh did you not test fully before approving the changes?

Well it's a good job you're testing me before I change your heart rate to 0.

**Comment by john-montgomery2003** [comment]
> _ No description provided. _

poor from you nick. Well detailed messages are important and allow maintainers to know what theyre looking at. Please do better or we will have to stop reviewing PR's from you.

**Comment by NicholasG04** [comment]
> > _ No description provided. _
> 
> poor from you nick. Well detailed messages are important and allow maintainers to know what theyre looking at. Please do better or we will have to stop reviewing PR's from you.

Shut up

**Comment by john-montgomery2003** [comment]
> > > _ No description provided. _
> > 
> > 
> > poor from you nick. Well detailed messages are important and allow maintainers to know what theyre looking at. Please do better or we will have to stop reviewing PR's from you.
> 
> Shut up

i will close and report for abusive language if you dont shut the fuck up and stop

**Comment by RealJammy** [comment]
> Apart from the fact it doesn't work and failed all of the checks.

nick moment

**Comment by NicholasG04** [comment]
It works perfectly.

**Comment by RealJammy** [comment]
> It works perfectly.

If only you could get bitches as well as you could code...

**Pull request merged**
