### PR TITLE
Paying respects to Queen Elizabeth II

### PR DESCRIPTION
**Pull request by RealJammy**

### CODE REVIEW

**Review by JoshHeng — APPROVED** [review]
Lgtm!

**Comment by NicholasG04** [comment]
image
eh

**Comment by Modlizard** [comment]
This looks mid at best

**Comment by RealJammy** [comment]
> This looks mid at best

I find this slanderous.

**Comment by jmontg03** [comment]
This is a dead repo, please archive

**Comment by Modlizard** [comment]
> This is a dead repo, please archive

This was stated by a dead account, please archive

**Comment by NicholasG04** [comment]
> This is a dead repo, please archive 

John, thanks.

**Pull request closed without merging**
