### PR TITLE
Feat/onefuckingword

### LINKED ISSUE #182: Add Adam to thanks list

### PR DESCRIPTION
**Pull request by JacquesRW**
nice to see this branch still has relevance. also josh having his surname and no one else was weird

Closes #182

### CODE REVIEW

**Comment by john-montgomery2003** [comment]
I disagree

**Comment by JacquesRW** [comment]
it looks weird to be the only name with a surname

**Comment by NicholasG04** [comment]
this is an old branch you MELT

**Comment by JacquesRW** [comment]
good point

**Pull request closed without merging**
